# Generated by Django 3.2 on 2022-02-07 02:19

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('modified_by', models.BigIntegerField()),
                ('entity_id', models.BigIntegerField()),
                ('serialized_data', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Biro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ithc_biro', models.BigIntegerField()),
                ('rcc', models.IntegerField(blank=True, null=True)),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('sub_group_code', models.CharField(max_length=10)),
                ('group_code', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('all_object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Coa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(blank=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('definition', models.CharField(blank=True, max_length=1000, null=True)),
                ('hyperion_name', models.CharField(max_length=200)),
                ('is_capex', models.BooleanField(default=False)),
                ('minimum_item_origin', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(blank=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('year', models.IntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notification', models.BooleanField(default=False)),
                ('due_date', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('all_object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(blank=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('product_code', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('all_object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(blank=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('itfam_id', models.CharField(max_length=200)),
                ('project_name', models.CharField(max_length=200)),
                ('project_description', models.CharField(max_length=500)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('total_investment_value', models.BigIntegerField()),
                ('is_tech', models.BooleanField(default=False)),
                ('biro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.biro')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(blank=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('employee_id', models.BigIntegerField(blank=True, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('initial', models.CharField(blank=True, max_length=10, null=True)),
                ('eselon', models.CharField(blank=True, max_length=10, null=True)),
                ('role', models.CharField(default='user', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(blank=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('dcsp_id', models.CharField(max_length=200)),
                ('planning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.planning')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_detail', to='api.project')),
                ('project_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.projecttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.strategy'),
        ),
        migrations.CreateModel(
            name='Monitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monitoring_status', models.CharField(max_length=50)),
                ('pic_employee_id', models.BigIntegerField(blank=True)),
                ('pic_initial', models.CharField(blank=True, max_length=10)),
                ('pic_display_name', models.CharField(blank=True, max_length=50)),
                ('biro', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.biro')),
                ('planning', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.planning')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(blank=True)),
                ('updated_by', models.BigIntegerField(blank=True, null=True)),
                ('expense_type', models.CharField(max_length=200)),
                ('planning_q1', models.BigIntegerField(blank=True, default=0)),
                ('planning_q2', models.BigIntegerField(blank=True, default=0)),
                ('planning_q3', models.BigIntegerField(blank=True, default=0)),
                ('planning_q4', models.BigIntegerField(blank=True, default=0)),
                ('realization_jan', models.BigIntegerField(blank=True, default=0)),
                ('realization_feb', models.BigIntegerField(blank=True, default=0)),
                ('realization_mar', models.BigIntegerField(blank=True, default=0)),
                ('realization_apr', models.BigIntegerField(blank=True, default=0)),
                ('realization_may', models.BigIntegerField(blank=True, default=0)),
                ('realization_jun', models.BigIntegerField(blank=True, default=0)),
                ('realization_jul', models.BigIntegerField(blank=True, default=0)),
                ('realization_aug', models.BigIntegerField(blank=True, default=0)),
                ('realization_sep', models.BigIntegerField(blank=True, default=0)),
                ('realization_oct', models.BigIntegerField(blank=True, default=0)),
                ('realization_nov', models.BigIntegerField(blank=True, default=0)),
                ('realization_dec', models.BigIntegerField(blank=True, default=0)),
                ('switching_in', models.BigIntegerField(blank=True, default=0)),
                ('switching_out', models.BigIntegerField(blank=True, default=0)),
                ('top_up', models.BigIntegerField(blank=True, default=0)),
                ('returns', models.BigIntegerField(blank=True, default=0)),
                ('allocate', models.BigIntegerField(blank=True, default=0)),
                ('coa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.coa')),
                ('project_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='api.projectdetail')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
