# Generated by Django 3.2 on 2022-01-18 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Coa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('definition', models.CharField(max_length=200)),
                ('hyperion_name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('is_capex', models.BooleanField(default=False)),
                ('minimum_item_origin', models.IntegerField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(blank=True)),
                ('updated_by', models.BigIntegerField(blank=True)),
                ('Year', models.IntegerField()),
                ('IsActive', models.BooleanField()),
                ('DueDate', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(blank=True)),
                ('updated_by', models.BigIntegerField(blank=True)),
                ('ITFamId', models.CharField(max_length=200)),
                ('ProjectName', models.CharField(max_length=200)),
                ('ProjectDescription', models.CharField(max_length=500)),
                ('BiroId', models.BigIntegerField()),
                ('RCC', models.IntegerField()),
                ('StartYear', models.IntegerField()),
                ('EndYear', models.IntegerField()),
                ('TotalInvestmentValue', models.BigIntegerField()),
                ('isTech', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(blank=True)),
                ('updated_by', models.BigIntegerField(blank=True)),
                ('DcspId', models.CharField(max_length=200)),
                ('Year', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(blank=True)),
                ('updated_by', models.BigIntegerField(blank=True)),
                ('ExpenseType', models.CharField(max_length=200)),
                ('PlanningNomimal', models.CharField(max_length=200)),
                ('PlanningQ1', models.BigIntegerField()),
                ('PlanningQ2', models.BigIntegerField()),
                ('PlanningQ3', models.BigIntegerField()),
                ('PlanningQ4', models.BigIntegerField()),
                ('RealizationNominal', models.BigIntegerField()),
                ('RealizationJan', models.BigIntegerField()),
                ('RealizationFeb', models.BigIntegerField()),
                ('RealizationMar', models.BigIntegerField()),
                ('RealizationApr', models.BigIntegerField()),
                ('RealizationMay', models.BigIntegerField()),
                ('RealizationJun', models.BigIntegerField()),
                ('RealizationJul', models.BigIntegerField()),
                ('RealizationAug', models.BigIntegerField()),
                ('RealizationSep', models.BigIntegerField()),
                ('RealizationOct', models.BigIntegerField()),
                ('RealizationNov', models.BigIntegerField()),
                ('RealizationDec', models.BigIntegerField()),
                ('SwitchingIn', models.BigIntegerField()),
                ('SwitchingOut', models.BigIntegerField()),
                ('TopUp', models.BigIntegerField()),
                ('Return', models.BigIntegerField()),
                ('Allocate', models.BigIntegerField()),
                ('CoaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.coa')),
                ('ProjectDetailId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.projectdetail')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
