# Generated by Django 3.2 on 2022-02-08 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='itfam_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
