# Generated by Django 3.2 on 2022-01-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coa',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='coa',
            name='definition',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
