# Generated by Django 3.2 on 2022-01-18 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='BiroId',
            new_name='biro_id',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='EndYear',
            new_name='end_year',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='isTech',
            new_name='is_tech',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='ITFamId',
            new_name='itfam_id',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='ProjectDescription',
            new_name='project_description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='ProjectName',
            new_name='project_name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='RCC',
            new_name='rcc',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='StartYear',
            new_name='start_year',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='TotalInvestmentValue',
            new_name='total_investment_value',
        ),
        migrations.RenameField(
            model_name='projectdetail',
            old_name='DcspId',
            new_name='dcsp_id',
        ),
        migrations.RenameField(
            model_name='projectdetail',
            old_name='Year',
            new_name='year',
        ),
    ]
