# Generated by Django 3.2 on 2022-01-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_by',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
