# Generated by Django 3.2 on 2022-01-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coa',
            name='minimum_item_origin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
