# Generated by Django 3.2 on 2022-01-22 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='action_id',
            new_name='action',
        ),
        migrations.RenameField(
            model_name='auditlog',
            old_name='table_id',
            new_name='table',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='coa_id',
            new_name='coa',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='project_detail_id',
            new_name='project_detail',
        ),
        migrations.RenameField(
            model_name='monitoring',
            old_name='monitoring_status_id',
            new_name='monitoring_status',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='strategy_id',
            new_name='strategy',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='projectdetail',
            old_name='planning_id',
            new_name='planning',
        ),
        migrations.RenameField(
            model_name='projectdetail',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='projectdetail',
            old_name='project_type_id',
            new_name='project_type',
        ),
    ]
