# Generated by Django 3.2 on 2022-01-25 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planning',
            name='year',
            field=models.IntegerField(unique=True),
        ),
    ]
