# Generated by Django 3.2 on 2022-02-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoring',
            name='pic_display_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='monitoring',
            name='pic_employee_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monitoring',
            name='pic_initial',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
