# Generated by Django 3.2 on 2022-02-04 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_projectdetail_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='eselon',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='initial',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
