# Generated by Django 3.2 on 2022-02-15 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220215_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoring',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_fk_created', to='api.user'),
        ),
        migrations.AddField(
            model_name='monitoring',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_fk_updated', to='api.user'),
        ),
    ]
