# Generated by Django 3.2 on 2022-01-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_budget_coa_planning_projectdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.BigIntegerField(blank=True, default='')),
                ('updated_by', models.BigIntegerField(blank=True, default='')),
                ('ITFamId', models.CharField(max_length=200)),
                ('ProjectName', models.CharField(max_length=200)),
                ('ProjectDescription', models.CharField(max_length=500)),
                ('BiroId', models.BigIntegerField()),
                ('RCC', models.IntegerField()),
                ('StartYear', models.IntegerField()),
                ('EndYear', models.IntegerField()),
                ('TotalInvestmentValue', models.BigIntegerField()),
                ('isTech', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='planning',
            name='LastModifiedBy',
        ),
        migrations.AddField(
            model_name='planning',
            name='created_by',
            field=models.BigIntegerField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='planning',
            name='updated_by',
            field=models.BigIntegerField(blank=True, default=''),
        ),
    ]
